name: Deploy Lambda

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    defaults:
      run:
        working-directory: ./node

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Dump .env
      run: echo "${{ secrets.ENV }}" > .env

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: npm install

    - name: deploy
      run: npm run deploy
